In [7]:
from intrinsic_alignments.shape_models.density_profiles import cusped_density
from intrinsic_alignments.shape_models.utils import projected_b_to_a
from intrinsic_alignments.shape_models.tensor_calculations import inertia_tensors, principal_axes_from_inertia_tensors

In [11]:
d = cusped_density()
coords = np.stack((d.sample(10000),d.sample(10000)))

In [12]:
t = inertia_tensors(coords)

In [13]:
principal_axes_from_inertia_tensors(t)

(array([[ 0.27693625, -0.93505352, -0.22131704],
        [-0.80205056, -0.32000033,  0.50429622]]),
 array([59257.52252059, 63654.41809322]))

In [14]:
t

array([[[ 34080.77775594,  -6762.9849128 ,  -2930.63930461],
        [ -6762.9849128 ,  56122.51541942,   4782.65826963],
        [ -2930.63930461,   4782.65826963,  35383.88946994]],

       [[ 49969.93750111,   7921.09591125, -16737.96411629],
        [  7921.09591125,  35334.05504066,  -5372.64784831],
        [-16737.96411629,  -5372.64784831,  33624.56275224]]])